name: acil_durum_takip
description: "Acil durum çantası takip uygulaması"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Icons
  font_awesome_flutter: ^10.7.0
  
  # Notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  
  # File & Path
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  
  # Utils
  intl: ^0.20.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  
  assets:
    - assets/lang/tr.json
    - assets/lang/en.json
    - assets/lang/hi.json
    - assets/lang/es.json
    - assets/lang/ar.json
    - assets/lang/pt.json
    - assets/lang/it.json
    - assets/lang/fr.json
    - assets/lang/de.json
    - assets/lang/ja.json
    - assets/lang/ko.json
    - assets/lang/fa.json
    - assets/lang/uk.json
    - assets/lang/bn.json
    - assets/lang/ur.json
    - assets/lang/my.json
    - assets/lang/am.json
    - assets/lang/so.json
    - assets/lang/zh.json
    - assets/lang/ru.json
